#!/usr/bin/env bash
# scripts/sync-core.sh — report how this repo's vendored core/ compares with upstream
# dotfiles-core. REPORT ONLY: it no longer pulls, and it never writes core.lock.
# ──────────────────────────────────────────────────────────────────────────────
# THE PULL IS RETIRED (dotfiles-core#676). This used to be the fleet's ONE sanctioned
# second writer into core/: a `git subtree pull --squash` that then stamped all four
# core.lock fields. VENDORING.md sanctioned it — unlike the three retired `make core-lock`
# generators — precisely because it wrote Core's format from WHAT IT ACTUALLY PULLED
# (core_sha from the squash commit's git-subtree-split trailer, core_version from the tree
# now on disk), so the lock could not describe a commit its own core/ did not contain.
#
# A filtered vendor removes exactly that property. Core stopped vendoring its whole tree:
# core/ is now `core.manifest` ∪ `core.vendor`, roughly two thirds of it. A subtree pull
# MERGES the whole upstream tree and has no way to apply that filter, so "what it actually
# pulled" is, by construction, no longer what a vendored core/ should contain. The first
# pull after this repo's lock moved to a filtering commit would land every upstream file
# against an expectation of the subset, and core-integrity would report TAMPERED —
# correctly, and with no hand-edit anywhere.
#
# Teaching it to filter was the other option and is worse: it would make this repo a second
# PRODUCER of Core's format, which is what the sanction was never extended to. Two
# implementations of one filter is the failure dotfiles-core#556 exists to prevent — a
# producer computing a different subset passes its own assertion and is reported TAMPERED
# by an unrelated command later. Upstream now has exactly one producer,
# core_vendor_materialize in scripts/lib/core-vendor.sh.
#
# WHAT REPLACES IT: the fan-out, like every other repo. A dotfiles-core release opens a
# core.lock-bump PR here automatically (sync-fanout.yml); merge it. In practice that is
# already how Core arrives — every one of the last ten core.lock writes in this repo came
# from the fan-out, not from this script.
#
#   scripts/sync-core.sh                  # report: is core/ behind upstream?
#   scripts/sync-core.sh --check          # same thing; kept so existing callers still work
#   scripts/sync-core.sh <remote-or-url>  # compare against a specific remote / URL / clone
#   scripts/sync-core.sh --ref vX.Y.Z     # compare against an EXACT tag instead of core_ref
#
# Exit: 0 = reported (whether current or behind). 2 = usage/precondition error. It never
# writes, so there is nothing to review and nothing to commit.
#
# The companion subtree is UNAFFECTED — scripts/sync-companion.sh still pulls, because htpx
# vendors its whole tree and has no allowlist. Do not "fix" that one to match this.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

PREFIX="core"
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
LOCK="$REPO_ROOT/core.lock"
DEFAULT_REPO="dotgibson/dotfiles-core"
cd -- "$REPO_ROOT"

die() { echo "sync-core: $*" >&2; exit 1; }

REMOTE_ARG=""
REF_OPT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    # Accepted and ignored: the pull is gone, so every run is what --check used to mean.
    # Kept rather than rejected because the Makefile, CONTRIBUTING.md and
    # check-core-freshness.sh's own nudge have all pointed at it.
    --check) ;;
    --ref)
      shift
      [[ $# -gt 0 ]] || die "--ref needs a value (a branch or tag)"
      case "$1" in -*) die "--ref needs a value, got another option: $1" ;; esac
      REF_OPT="$1" ;;
    --ref=*)
      REF_OPT="${1#--ref=}"
      [[ -n "$REF_OPT" ]] || die "--ref= needs a non-empty value (a branch or tag)" ;;
    -h | --help) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *) [[ -z "$REMOTE_ARG" ]] || die "only one remote/URL may be given"; REMOTE_ARG="$1" ;;
  esac
  shift
done

[[ -f "$LOCK" ]] || die "$LOCK not found — is the core subtree vendored?"
[[ -d "$REPO_ROOT/$PREFIX" ]] || die "$PREFIX/ not present — nothing to sync."

lock_field() { sed -n -E "s/^$1=//p" "$LOCK" | head -n1; }
# core_ref, falling back to the legacy core_branch. dotfiles-core#453 renamed the field
# because the name was wrong: the fan-out writes a PINNED COMMIT there, not a branch, so
# a lock generated by a release recorded a SHA in a field documented as a branch.
#
# BOTH names are read, and that is not belt-and-braces — it is what makes the rollout
# order not matter. This repo vendors Core on its own schedule (that is what this script
# is for), so a lock written before the rename and a lock written after it both exist in
# the wild, and there is no moment when we can assume which one is on disk. Reading only
# the new name would have made `sync-core.sh` die on every repo that had not yet synced —
# from a line whose whole job is to report a missing field.
branch="$(lock_field core_ref)"
[[ -n "$branch" ]] || branch="$(lock_field core_branch)"
old_sha="$(lock_field core_sha)"
[[ -n "$branch" ]] || die "neither core_ref nor core_branch is present in $LOCK"
# The rewrites below REPLACE existing lines rather than inserting, so a lock missing
# core_sha would let the pull succeed and leave the lock silently stale. Same guard
# sync-companion.sh carries, for the same reason.
[[ -n "$old_sha" ]] || die "core_sha missing/empty in $LOCK — add a 'core_sha=' line before syncing."

REF="${REF_OPT:-$branch}"

# Remote precedence: explicit arg → a git remote literally named dotfiles-core →
# the GitHub HTTPS URL. The arg lets you sync from a local clone without editing the lock.
if [[ -n "$REMOTE_ARG" ]]; then
  remote="$REMOTE_ARG"
elif git remote get-url "$DEFAULT_REPO" >/dev/null 2>&1; then
  remote="$DEFAULT_REPO"
else
  remote="https://github.com/$DEFAULT_REPO.git"
fi

echo "sync-core: prefix=$PREFIX  remote=$remote  ref=$REF"
echo "sync-core: locked at  $old_sha"

# ALWAYS the report, whether or not --check was passed. --check used to be the read-only
# mode and the bare run pulled; the pull is gone, so the two collapse. The flag is kept
# rather than rejected because test/check-core-freshness.sh's nudge, the Makefile and
# CONTRIBUTING.md have all pointed at it, and breaking those to make a point about an
# option name helps nobody.
#
# DELEGATED to test/check-core-freshness.sh rather than re-implemented here.
#
# This block used to resolve the ref itself, with `refs/heads/<core_branch>` as the
# default case — and core_branch is a pinned SHA after every fleet sync, so it
# matched nothing. Two copies of the same wrong assumption is what made that bug
# survive review, so there is now exactly one resolver and this calls it.
#
# Its contract: 0 current / 2 behind / 1 hard failure. Translate to this script's
# voice and always exit 0 — this is informational, and a "behind" result is the
# expected answer most of the time, not an error.
checker="$REPO_ROOT/test/check-core-freshness.sh"
[[ -x "$checker" ]] || die "$checker not found — cannot report freshness."
rc=0
CORE_UPSTREAM="$remote" CORE_BRANCH="${REF_OPT:-$branch}" "$checker" || rc=$?
case "$rc" in
  0) echo "sync-core: up to date — the vendored core/ matches upstream." ;;
  2) echo "sync-core: upstream is AHEAD of the lock." ;;
  *) die "freshness check failed (exit $rc) — see above." ;;
esac

# Say what to do about it, every time, including when up to date — someone reaching for
# this script is asking "how do I move Core?", and the answer changed.
cat <<EOF

sync-core: this script no longer pulls. Core arrives here by FAN-OUT:
  a dotfiles-core release opens a core.lock-bump PR in this repo automatically
  (sync-fanout.yml). Merge it, then: make lint && make test

  Why: a vendored core/ is a FILTERED subset of upstream since dotfiles-core#676
  (core.manifest + core.vendor). 'git subtree pull' merges the whole tree and cannot
  apply that filter, so pulling would land every upstream file against an expectation
  of the subset and core-integrity would report TAMPERED. See the header of this file.

  To pull anyway you would have to bypass this deliberately — don't. If the fan-out PR
  has not arrived, the fix is upstream (dotfiles-core: make sync), not here.
EOF
exit 0
